# Generated by Django 5.2.9 on 2026-01-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='effective_price',
            field=models.DecimalField(db_index=True, decimal_places=0, default=0, editable=False, max_digits=12, verbose_name='Giá thực tế'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['effective_price'], name='catalog_pro_effecti_574fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'effective_price'], name='catalog_pro_is_acti_926588_idx'),
        ),
    ]
