# Generated by Django 5.2.9 on 2026-01-04 12:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_populate_effective_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStat',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='catalog.product', verbose_name='Sản phẩm')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('sold_count', models.PositiveIntegerField(default=0, verbose_name='Đã bán')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, verbose_name='Điểm TB')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='Số đánh giá')),
            ],
            options={
                'verbose_name': 'Thống kê sản phẩm',
                'verbose_name_plural': 'Thống kê sản phẩm',
            },
        ),
    ]
