# Generated by Django 5.2.9 on 2026-01-09 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customersegment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_segment', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AddIndex(
            model_name='dailymetric',
            index=models.Index(fields=['-date'], name='analytics_d_date_cca0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymetric',
            index=models.Index(fields=['date', 'total_revenue'], name='analytics_d_date_61a720_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['-year', '-month'], name='analytics_m_year_a29db9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together={('year', 'month')},
        ),
        migrations.AddIndex(
            model_name='productanalytics',
            index=models.Index(fields=['-total_revenue'], name='analytics_p_total_r_698134_idx'),
        ),
        migrations.AddIndex(
            model_name='productanalytics',
            index=models.Index(fields=['-performance_score'], name='analytics_p_perform_a374b3_idx'),
        ),
        migrations.AddIndex(
            model_name='productanalytics',
            index=models.Index(fields=['trending_up', '-revenue_30d'], name='analytics_p_trendin_3c630d_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuebreakdown',
            index=models.Index(fields=['-date', 'breakdown_type'], name='analytics_r_date_10b1eb_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuebreakdown',
            index=models.Index(fields=['breakdown_type', '-revenue'], name='analytics_r_breakdo_df088f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='revenuebreakdown',
            unique_together={('date', 'breakdown_type', 'dimension_key')},
        ),
        migrations.AddIndex(
            model_name='salesfunnel',
            index=models.Index(fields=['-date'], name='analytics_s_date_5cd24f_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficsource',
            index=models.Index(fields=['-date', 'source'], name='analytics_t_date_b7a81c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trafficsource',
            unique_together={('date', 'source')},
        ),
        migrations.AddIndex(
            model_name='customersegment',
            index=models.Index(fields=['segment'], name='analytics_c_segment_407fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='customersegment',
            index=models.Index(fields=['-total_spent'], name='analytics_c_total_s_ee2b82_idx'),
        ),
        migrations.AddIndex(
            model_name='customersegment',
            index=models.Index(fields=['churn_risk'], name='analytics_c_churn_r_5a67fa_idx'),
        ),
    ]
