# Generated by Django 5.2.9 on 2026-01-03 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='Mã đơn hàng')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('processing', 'Đang xử lý'), ('ready_to_ship', 'Chờ giao hàng'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền'), ('failed', 'Thất bại')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('source', models.CharField(choices=[('web', 'Website'), ('mobile', 'Ứng dụng mobile'), ('admin', 'Admin tạo'), ('api', 'API')], default='web', max_length=20, verbose_name='Nguồn đơn')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Tên người nhận')),
                ('phone', models.CharField(db_index=True, max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('ward', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('city', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('country', models.CharField(default='Vietnam', max_length=50, verbose_name='Quốc gia')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Mã bưu điện')),
                ('district_id', models.IntegerField(verbose_name='Mã quận GHN')),
                ('ward_code', models.CharField(max_length=20, verbose_name='Mã phường GHN')),
                ('payment_method', models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('vnpay', 'VNPay'), ('momo', 'MoMo')], db_index=True, default='cod', max_length=20, verbose_name='Phương thức thanh toán')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('pending', 'Đang xử lý'), ('paid', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại'), ('partial_refund', 'Hoàn một phần'), ('refunded', 'Đã hoàn tiền')], db_index=True, default='unpaid', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tạm tính')),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Phí vận chuyển')),
                ('insurance_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Phí bảo hiểm')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giảm giá')),
                ('tax', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thuế')),
                ('total', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng cộng')),
                ('currency', models.CharField(default='VND', max_length=3, verbose_name='Đơn vị tiền')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='Mã giảm giá')),
                ('coupon_discount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giảm từ coupon')),
                ('tracking_code', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Mã vận đơn')),
                ('shipping_provider', models.CharField(blank=True, max_length=20, verbose_name='Đơn vị vận chuyển')),
                ('customer_note', models.TextField(blank=True, verbose_name='Ghi chú khách hàng')),
                ('admin_note', models.TextField(blank=True, verbose_name='Ghi chú nội bộ')),
                ('is_priority', models.BooleanField(default=False, verbose_name='Đơn ưu tiên')),
                ('is_gift', models.BooleanField(default=False, verbose_name='Đơn quà tặng')),
                ('gift_message', models.TextField(blank=True, verbose_name='Lời nhắn quà tặng')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xác nhận')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thanh toán')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian giao cho vận chuyển')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian giao hàng')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn thành')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hủy')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Lý do hủy')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL, verbose_name='Người hủy')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketing.coupon', verbose_name='Mã khuyến mãi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
                'permissions': [('can_view_all_orders', 'Can view all orders'), ('can_cancel_orders', 'Can cancel orders'), ('can_refund_orders', 'Can refund orders'), ('can_export_orders', 'Can export orders')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('product_sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('product_image', models.URLField(blank=True, max_length=500, verbose_name='Hình ảnh')),
                ('product_attributes', models.JSONField(blank=True, default=dict, verbose_name='Thuộc tính')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Đơn giá')),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá gốc')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giảm giá')),
                ('returned_quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng đã trả')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong đơn',
                'verbose_name_plural': 'Sản phẩm trong đơn',
            },
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('note_type', models.CharField(choices=[('general', 'Chung'), ('payment', 'Thanh toán'), ('shipping', 'Vận chuyển'), ('customer', 'Khách hàng'), ('issue', 'Vấn đề')], default='general', max_length=20, verbose_name='Loại ghi chú')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('is_private', models.BooleanField(default=True, verbose_name='Chỉ admin xem')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Ghi chú đơn hàng',
                'verbose_name_plural': 'Ghi chú đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('old_status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('processing', 'Đang xử lý'), ('ready_to_ship', 'Chờ giao hàng'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền'), ('failed', 'Thất bại')], max_length=20, verbose_name='Trạng thái cũ')),
                ('new_status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('processing', 'Đang xử lý'), ('ready_to_ship', 'Chờ giao hàng'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền'), ('failed', 'Thất bại')], max_length=20, verbose_name='Trạng thái mới')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thay đổi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Lịch sử trạng thái',
                'verbose_name_plural': 'Lịch sử trạng thái',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', '-created_at'], name='orders_orde_payment_8bdf8b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method', 'status'], name='orders_orde_payment_e02dad_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='orders_orde_created_f0ce29_idx'),
        ),
    ]
