# Generated by Django 5.2.9 on 2026-01-09 02:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='Order Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready_to_ship', 'Ready to Ship'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('web', 'Website'), ('mobile', 'Mobile App'), ('admin', 'Admin Created'), ('api', 'API')], default='web', max_length=20, verbose_name='Source')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Recipient Name')),
                ('phone', models.CharField(db_index=True, max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('ward', models.CharField(max_length=100, verbose_name='Ward')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(default='Vietnam', max_length=50, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Postal Code')),
                ('district_id', models.IntegerField(blank=True, null=True, verbose_name='GHN District ID')),
                ('ward_code', models.CharField(blank=True, max_length=20, verbose_name='GHN Ward Code')),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('vnpay', 'VNPay'), ('momo', 'MoMo'), ('stripe', 'Stripe (Card)')], db_index=True, default='cod', max_length=20, verbose_name='Payment Method')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Processing'), ('paid', 'Paid'), ('failed', 'Payment Failed'), ('partial_refund', 'Partial Refund'), ('refunded', 'Refunded')], db_index=True, default='unpaid', max_length=20, verbose_name='Payment Status')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Subtotal')),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Shipping Fee')),
                ('insurance_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Insurance Fee')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Discount')),
                ('tax', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tax')),
                ('total', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Total')),
                ('currency', models.CharField(default='VND', max_length=3, verbose_name='Currency')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='Coupon Code')),
                ('coupon_discount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Coupon Discount')),
                ('tracking_code', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Tracking Code')),
                ('shipping_provider', models.CharField(blank=True, max_length=20, verbose_name='Shipping Provider')),
                ('customer_note', models.TextField(blank=True, verbose_name='Customer Note')),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin Note')),
                ('is_priority', models.BooleanField(default=False, verbose_name='Priority Order')),
                ('is_gift', models.BooleanField(default=False, verbose_name='Gift Order')),
                ('gift_message', models.TextField(blank=True, verbose_name='Gift Message')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Shipped At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Cancel Reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
                'permissions': [('can_view_all_orders', 'Can view all orders'), ('can_cancel_orders', 'Can cancel orders'), ('can_refund_orders', 'Can refund orders')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('product_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Product ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('product_sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('product_image', models.URLField(blank=True, max_length=500, verbose_name='Image')),
                ('product_attributes', models.JSONField(blank=True, default=dict, verbose_name='Attributes')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Unit Price')),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Original Price')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Discount')),
                ('returned_quantity', models.PositiveIntegerField(default=0, verbose_name='Returned Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('note_type', models.CharField(choices=[('general', 'General'), ('payment', 'Payment'), ('shipping', 'Shipping'), ('customer', 'Customer'), ('issue', 'Issue')], default='general', max_length=20, verbose_name='Type')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_private', models.BooleanField(default=True, verbose_name='Private')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Note',
                'verbose_name_plural': 'Order Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('old_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready_to_ship', 'Ready to Ship'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('failed', 'Failed')], max_length=20, verbose_name='Old Status')),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready_to_ship', 'Ready to Ship'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('failed', 'Failed')], max_length=20, verbose_name='New Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', '-created_at'], name='orders_orde_payment_8bdf8b_idx'),
        ),
    ]
