# Generated by Django 5.2.9 on 2026-01-09 04:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('ghn', 'GHN'), ('ghtk', 'GHTK'), ('vtp', 'Viettel Post'), ('vnpost', 'VNPost'), ('jnt', 'J&T Express'), ('ninjavan', 'Ninja Van'), ('manual', 'Manual')], db_index=True, default='ghn', max_length=20, verbose_name='Provider')),
                ('tracking_code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Tracking Code')),
                ('provider_order_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Provider Order ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picking', 'Picking Up'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('sorting', 'Sorting'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('waiting_return', 'Waiting Return'), ('returning', 'Returning'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('exception', 'Exception')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('provider_status', models.CharField(blank=True, max_length=50, verbose_name='Provider Status')),
                ('weight', models.PositiveIntegerField(default=500, verbose_name='Weight (g)')),
                ('dimensions', models.JSONField(blank=True, default=dict, verbose_name='Dimensions')),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Shipping Fee')),
                ('insurance_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Insurance Fee')),
                ('cod_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='COD Fee')),
                ('total_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total Fee')),
                ('cod_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='COD Amount')),
                ('cod_collected', models.BooleanField(default=False, verbose_name='COD Collected')),
                ('cod_transferred', models.BooleanField(default=False, verbose_name='COD Transferred')),
                ('cod_transfer_date', models.DateField(blank=True, null=True, verbose_name='COD Transfer Date')),
                ('provider_data', models.JSONField(blank=True, default=dict, verbose_name='Provider Data')),
                ('service_id', models.IntegerField(blank=True, null=True, verbose_name='Service ID')),
                ('service_type', models.CharField(blank=True, max_length=50, verbose_name='Service Type')),
                ('expected_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Expected Delivery')),
                ('delivery_attempts', models.PositiveIntegerField(default=0, verbose_name='Delivery Attempts')),
                ('max_delivery_attempts', models.PositiveIntegerField(default=3, verbose_name='Max Attempts')),
                ('required_note', models.CharField(default='CHOTHUHANG', max_length=50, verbose_name='Required Note')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Picked Up At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Returned At')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('last_location', models.CharField(blank=True, max_length=255, verbose_name='Last Location')),
                ('last_status_update', models.DateTimeField(blank=True, null=True, verbose_name='Last Update')),
                ('fail_reason', models.TextField(blank=True, verbose_name='Fail Reason')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Cancel Reason')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('attempt_number', models.PositiveIntegerField(verbose_name='Attempt #')),
                ('attempted_at', models.DateTimeField(verbose_name='Attempted At')),
                ('fail_reason', models.CharField(choices=[('not_home', 'No One Home'), ('wrong_address', 'Wrong Address'), ('phone_unreachable', 'Phone Unreachable'), ('refused', 'Refused'), ('insufficient_cod', 'Insufficient COD'), ('rescheduled', 'Rescheduled'), ('weather', 'Bad Weather'), ('other', 'Other')], max_length=20, verbose_name='Fail Reason')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('rescheduled_to', models.DateTimeField(blank=True, null=True, verbose_name='Rescheduled To')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_logs', to='shipping.shipment', verbose_name='Shipment')),
            ],
            options={
                'verbose_name': 'Delivery Attempt',
                'verbose_name_plural': 'Delivery Attempts',
                'ordering': ['shipment', 'attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='CODReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('provider', models.CharField(choices=[('ghn', 'GHN'), ('ghtk', 'GHTK'), ('vtp', 'Viettel Post'), ('vnpost', 'VNPost'), ('jnt', 'J&T Express'), ('ninjavan', 'Ninja Van'), ('manual', 'Manual')], max_length=20, verbose_name='Provider')),
                ('reconciliation_date', models.DateField(db_index=True, verbose_name='Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('transferred', 'Transferred'), ('disputed', 'Disputed')], default='pending', max_length=20, verbose_name='Status')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total Orders')),
                ('total_cod', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Total COD')),
                ('total_shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Total Shipping')),
                ('net_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Net Amount')),
                ('transferred_at', models.DateTimeField(blank=True, null=True, verbose_name='Transferred At')),
                ('transfer_reference', models.CharField(blank=True, max_length=100, verbose_name='Transfer Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('shipments', models.ManyToManyField(blank=True, related_name='cod_reconciliations', to='shipping.shipment', verbose_name='Shipments')),
            ],
            options={
                'verbose_name': 'COD Reconciliation',
                'verbose_name_plural': 'COD Reconciliations',
                'ordering': ['-reconciliation_date'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('status', models.CharField(db_index=True, max_length=50, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='Occurred At')),
                ('provider_data', models.JSONField(blank=True, default=dict, verbose_name='Provider Data')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipping.shipment', verbose_name='Shipment')),
            ],
            options={
                'verbose_name': 'Shipment Event',
                'verbose_name_plural': 'Shipment Events',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order', 'status'], name='shipping_sh_order_i_242975_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['provider', 'status'], name='shipping_sh_provide_a2dad6_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', '-created_at'], name='shipping_sh_status_8a7968_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryattempt',
            unique_together={('shipment', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='codreconciliation',
            unique_together={('provider', 'reconciliation_date')},
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['shipment', '-occurred_at'], name='shipping_sh_shipmen_4d1b49_idx'),
        ),
    ]
