# Generated by Django 5.2.9 on 2026-01-03 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ghn', 'Giao Hàng Nhanh'), ('ghtk', 'Giao Hàng Tiết Kiệm'), ('vtp', 'Viettel Post'), ('vnpost', 'VNPost'), ('jnt', 'J&T Express'), ('ninjavan', 'Ninja Van'), ('best', 'BEST Express'), ('manual', 'Tự giao')], db_index=True, default='ghn', max_length=20, verbose_name='Nhà vận chuyển')),
                ('tracking_code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Mã vận đơn')),
                ('provider_order_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Mã đơn provider')),
                ('status', models.CharField(choices=[('pending', 'Chờ lấy hàng'), ('picking', 'Đang lấy hàng'), ('picked_up', 'Đã lấy hàng'), ('in_transit', 'Đang vận chuyển'), ('sorting', 'Đang phân loại'), ('out_for_delivery', 'Đang giao'), ('delivered', 'Đã giao'), ('failed', 'Giao thất bại'), ('waiting_return', 'Chờ trả hàng'), ('returning', 'Đang trả hàng'), ('returned', 'Đã trả hàng'), ('cancelled', 'Đã hủy'), ('exception', 'Ngoại lệ')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('provider_status', models.CharField(blank=True, max_length=50, verbose_name='Trạng thái gốc từ provider')),
                ('weight', models.PositiveIntegerField(default=500, help_text='Trọng lượng thực tế, đơn vị gram', verbose_name='Trọng lượng (g)')),
                ('dimensions', models.JSONField(blank=True, default=dict, help_text='{"length": cm, "width": cm, "height": cm}', verbose_name='Kích thước')),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Phí vận chuyển')),
                ('insurance_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Phí bảo hiểm')),
                ('cod_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Phí COD')),
                ('total_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng phí')),
                ('cod_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tiền thu hộ')),
                ('cod_collected', models.BooleanField(default=False, verbose_name='Đã thu COD')),
                ('cod_transferred', models.BooleanField(default=False, verbose_name='Đã chuyển COD về shop')),
                ('cod_transfer_date', models.DateField(blank=True, null=True, verbose_name='Ngày chuyển COD')),
                ('provider_data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu từ provider')),
                ('service_id', models.IntegerField(blank=True, null=True, verbose_name='Mã dịch vụ')),
                ('service_type', models.CharField(blank=True, max_length=50, verbose_name='Loại dịch vụ')),
                ('expected_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Dự kiến giao')),
                ('delivery_attempts', models.PositiveIntegerField(default=0, verbose_name='Số lần giao')),
                ('max_delivery_attempts', models.PositiveIntegerField(default=3, verbose_name='Số lần giao tối đa')),
                ('required_note', models.CharField(default='CHOTHUHANG', help_text='CHOTHUHANG, CHOXEMHANGKHONGTHU, KHONGCHOXEMHANG', max_length=50, verbose_name='Yêu cầu khi giao')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú giao hàng')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian lấy hàng')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian giao hàng')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian trả hàng')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hủy')),
                ('last_location', models.CharField(blank=True, max_length=255, verbose_name='Vị trí cuối')),
                ('last_status_update', models.DateTimeField(blank=True, null=True, verbose_name='Cập nhật cuối từ provider')),
                ('fail_reason', models.TextField(blank=True, verbose_name='Lý do giao thất bại')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Lý do hủy')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Vận chuyển',
                'verbose_name_plural': 'Vận chuyển',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('attempt_number', models.PositiveIntegerField(verbose_name='Lần giao thứ')),
                ('attempted_at', models.DateTimeField(verbose_name='Thời điểm giao')),
                ('fail_reason', models.CharField(choices=[('not_home', 'Không có người nhận'), ('wrong_address', 'Sai địa chỉ'), ('phone_unreachable', 'Không liên lạc được'), ('refused', 'Từ chối nhận hàng'), ('insufficient_cod', 'Không đủ tiền COD'), ('rescheduled', 'Hẹn giao lại'), ('weather', 'Thời tiết xấu'), ('other', 'Lý do khác')], max_length=20, verbose_name='Lý do thất bại')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('rescheduled_to', models.DateTimeField(blank=True, null=True, verbose_name='Lịch giao lại')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_logs', to='shipping.shipment', verbose_name='Vận chuyển')),
            ],
            options={
                'verbose_name': 'Lần giao hàng',
                'verbose_name_plural': 'Các lần giao hàng',
                'ordering': ['shipment', 'attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='CODReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('provider', models.CharField(choices=[('ghn', 'Giao Hàng Nhanh'), ('ghtk', 'Giao Hàng Tiết Kiệm'), ('vtp', 'Viettel Post'), ('vnpost', 'VNPost'), ('jnt', 'J&T Express'), ('ninjavan', 'Ninja Van'), ('best', 'BEST Express'), ('manual', 'Tự giao')], max_length=20, verbose_name='Nhà vận chuyển')),
                ('reconciliation_date', models.DateField(db_index=True, verbose_name='Ngày đối soát')),
                ('status', models.CharField(choices=[('pending', 'Chờ đối soát'), ('confirmed', 'Đã xác nhận'), ('transferred', 'Đã chuyển tiền'), ('disputed', 'Có tranh chấp')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Tổng đơn')),
                ('total_cod', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng tiền COD')),
                ('total_shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng phí ship')),
                ('net_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Số tiền thực nhận')),
                ('transferred_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm chuyển khoản')),
                ('transfer_reference', models.CharField(blank=True, max_length=100, verbose_name='Mã chuyển khoản')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('shipments', models.ManyToManyField(blank=True, related_name='cod_reconciliations', to='shipping.shipment', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Đối soát COD',
                'verbose_name_plural': 'Đối soát COD',
                'ordering': ['-reconciliation_date'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('status', models.CharField(db_index=True, max_length=50, verbose_name='Trạng thái')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Vị trí')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='Thời điểm')),
                ('provider_data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu gốc')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipping.shipment', verbose_name='Vận chuyển')),
            ],
            options={
                'verbose_name': 'Sự kiện vận chuyển',
                'verbose_name_plural': 'Sự kiện vận chuyển',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order', 'status'], name='shipping_sh_order_i_242975_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['provider', 'status'], name='shipping_sh_provide_a2dad6_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', '-created_at'], name='shipping_sh_status_8a7968_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['cod_amount', 'cod_collected'], name='shipping_sh_cod_amo_6eb9db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryattempt',
            unique_together={('shipment', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='codreconciliation',
            unique_together={('provider', 'reconciliation_date')},
        ),
        migrations.AddIndex(
            model_name='shipmentevent',
            index=models.Index(fields=['shipment', '-occurred_at'], name='shipping_sh_shipmen_4d1b49_idx'),
        ),
    ]
