# Generated by Django 5.2.9 on 2026-01-03 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItemLegacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Wishlist Item (Legacy)',
                'verbose_name_plural': 'Wishlist Items (Legacy)',
                'db_table': 'wishlist_wishlistitem',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Yêu thích', max_length=100, verbose_name='Tên danh sách')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_default', models.BooleanField(default=False, verbose_name='Mặc định')),
                ('is_public', models.BooleanField(default=False, verbose_name='Công khai')),
                ('share_token', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Token chia sẻ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Danh sách yêu thích',
                'verbose_name_plural': 'Danh sách yêu thích',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('priority', models.CharField(choices=[('high', 'Cao'), ('medium', 'Trung bình'), ('low', 'Thấp')], default='medium', max_length=10, verbose_name='Ưu tiên')),
                ('price_when_added', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá khi thêm')),
                ('lowest_price_seen', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá thấp nhất')),
                ('notify_on_sale', models.BooleanField(default=True, verbose_name='Thông báo khi giảm giá')),
                ('target_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá mong muốn')),
                ('last_price_alert_at', models.DateTimeField(blank=True, null=True, verbose_name='Thông báo giá cuối')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_entries', to='catalog.product', verbose_name='Sản phẩm')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlist.wishlist', verbose_name='Danh sách')),
            ],
            options={
                'verbose_name': 'Sản phẩm yêu thích',
                'verbose_name_plural': 'Sản phẩm yêu thích',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wishlist', '-created_at'], name='wishlist_wi_wishlis_5b886d_idx'), models.Index(fields=['product'], name='wishlist_wi_product_2322a5_idx')],
                'unique_together': {('wishlist', 'product')},
            },
        ),
    ]
