# Generated by Django 5.2.9 on 2026-01-09 04:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Favorites', max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('share_token', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Share Token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlists',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10, verbose_name='Priority')),
                ('price_when_added', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Price When Added')),
                ('lowest_price_seen', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Lowest Price')),
                ('notify_on_sale', models.BooleanField(default=True, verbose_name='Notify on Sale')),
                ('target_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Target Price')),
                ('last_price_alert_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Alert')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_entries', to='catalog.product', verbose_name='Product')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlist.wishlist', verbose_name='Wishlist')),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wishlist', '-created_at'], name='wishlist_wi_wishlis_5b886d_idx'), models.Index(fields=['product'], name='wishlist_wi_product_2322a5_idx')],
                'unique_together': {('wishlist', 'product')},
            },
        ),
    ]
