# Generated by Django 5.2.9 on 2026-01-03 17:06

import apps.common.core.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSummary',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='review_summary', serialize=False, to='catalog.product')),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_5', models.PositiveIntegerField(default=0)),
                ('rating_4', models.PositiveIntegerField(default=0)),
                ('rating_3', models.PositiveIntegerField(default=0)),
                ('rating_2', models.PositiveIntegerField(default=0)),
                ('rating_1', models.PositiveIntegerField(default=0)),
                ('avg_quality', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('avg_value', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('avg_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('verified_count', models.PositiveIntegerField(default=0)),
                ('with_images_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thống kê đánh giá',
                'verbose_name_plural': 'Thống kê đánh giá',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Tiêu đề')),
                ('comment', models.TextField(verbose_name='Nhận xét')),
                ('quality_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Chất lượng')),
                ('value_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Giá trị')),
                ('delivery_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Giao hàng')),
                ('is_verified_purchase', models.BooleanField(db_index=True, default=False, verbose_name='Đã mua hàng')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='Đã duyệt')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='Bị từ chối')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Lý do từ chối')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Duyệt lúc')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Hữu ích')),
                ('not_helpful_count', models.PositiveIntegerField(default=0, verbose_name='Không hữu ích')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Ghim')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('image', models.ImageField(upload_to=apps.common.core.storage.review_image_path, verbose_name='Hình ảnh')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Chú thích')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review', verbose_name='Đánh giá')),
            ],
            options={
                'verbose_name': 'Hình ảnh đánh giá',
                'verbose_name_plural': 'Hình ảnh đánh giá',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('is_official', models.BooleanField(default=False, verbose_name='Phản hồi chính thức')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.review', verbose_name='Đánh giá')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_replies', to=settings.AUTH_USER_MODEL, verbose_name='Người trả lời')),
            ],
            options={
                'verbose_name': 'Phản hồi đánh giá',
                'verbose_name_plural': 'Phản hồi đánh giá',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('offensive', 'Ngôn từ xúc phạm'), ('fake', 'Đánh giá giả'), ('irrelevant', 'Không liên quan'), ('other', 'Lý do khác')], max_length=20, verbose_name='Lý do')),
                ('details', models.TextField(blank=True, verbose_name='Chi tiết')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('reviewed', 'Đã xem xét'), ('resolved', 'Đã xử lý'), ('dismissed', 'Bác bỏ')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL, verbose_name='Người báo cáo')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review', verbose_name='Đánh giá')),
            ],
            options={
                'verbose_name': 'Báo cáo đánh giá',
                'verbose_name_plural': 'Báo cáo đánh giá',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('is_helpful', models.BooleanField(verbose_name='Hữu ích')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.review', verbose_name='Đánh giá')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL, verbose_name='Người vote')),
            ],
            options={
                'verbose_name': 'Vote đánh giá',
                'verbose_name_plural': 'Vote đánh giá',
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_approved', '-created_at'], name='reviews_rev_product_c28d88_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'rating'], name='reviews_rev_product_ddc882_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at'], name='reviews_rev_user_id_eeecea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewvote',
            unique_together={('review', 'user')},
        ),
    ]
