# Generated by Django 5.2.9 on 2026-01-09 04:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('allow_negative_stock', models.BooleanField(default=False, verbose_name='Allow Negative Stock')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_counts', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_counts', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Inventory Count',
                'verbose_name_plural': 'Inventory Counts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, help_text='Reserved for pending orders', verbose_name='Reserved Quantity')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, verbose_name='Low Stock Threshold')),
                ('reorder_point', models.PositiveIntegerField(default=5, verbose_name='Reorder Point')),
                ('reorder_quantity', models.PositiveIntegerField(default=50, verbose_name='Reorder Quantity')),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Restocked')),
                ('last_sold_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Sold')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Unit Cost')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.product', verbose_name='Product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Items',
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('reorder', 'Needs Reorder'), ('expiring', 'Expiring Soon')], max_length=20, verbose_name='Alert Type')),
                ('threshold', models.PositiveIntegerField(default=0, verbose_name='Threshold')),
                ('current_quantity', models.IntegerField(verbose_name='Current Quantity')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.stockitem', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Stock Alert',
                'verbose_name_plural': 'Stock Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('system_quantity', models.IntegerField(verbose_name='System Quantity')),
                ('counted_quantity', models.IntegerField(blank=True, null=True, verbose_name='Counted Quantity')),
                ('notes', models.TextField(blank=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Counted By')),
                ('inventory_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorycount', verbose_name='Inventory Count')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_items', to='inventory.stockitem', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Inventory Count Item',
                'verbose_name_plural': 'Inventory Count Items',
                'unique_together': {('inventory_count', 'stock')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('reserve', 'Reserve'), ('release', 'Release'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer')], default='adjustment', max_length=20, verbose_name='Type')),
                ('quantity_change', models.IntegerField(help_text='Positive=in, Negative=out', verbose_name='Quantity Change')),
                ('quantity_before', models.IntegerField(blank=True, null=True, verbose_name='Qty Before')),
                ('quantity_after', models.IntegerField(blank=True, null=True, verbose_name='Qty After')),
                ('reason', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('reservation', 'Reservation'), ('release', 'Release'), ('damage', 'Damage/Loss'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('initial', 'Initial Stock'), ('expired', 'Expired')], max_length=20, verbose_name='Reason')),
                ('reference', models.CharField(blank=True, db_index=True, help_text='Order ID, PO number, etc.', max_length=100, verbose_name='Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Unit Cost')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockitem', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock', '-created_at'], name='inventory_s_stock_i_cee363_idx'), models.Index(fields=['reason', '-created_at'], name='inventory_s_reason_748aca_idx'), models.Index(fields=['reference'], name='inventory_s_referen_16defd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['product'], name='inventory_s_product_6430b7_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['warehouse', 'quantity'], name='inventory_s_warehou_f597d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('product', 'warehouse')},
        ),
    ]
