# Generated by Django 5.2.9 on 2026-01-03 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên kho')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã kho')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('is_default', models.BooleanField(default=False, verbose_name='Kho mặc định')),
                ('allow_negative_stock', models.BooleanField(default=False, verbose_name='Cho phép âm kho')),
            ],
            options={
                'verbose_name': 'Kho hàng',
                'verbose_name_plural': 'Kho hàng',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên đợt kiểm')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('in_progress', 'Đang kiểm'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Hoàn thành')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_counts', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_counts', to='inventory.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Đợt kiểm kho',
                'verbose_name_plural': 'Đợt kiểm kho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, help_text='Số lượng đang chờ xử lý đơn hàng', verbose_name='Đã đặt trước')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, verbose_name='Ngưỡng cảnh báo')),
                ('reorder_point', models.PositiveIntegerField(default=5, verbose_name='Điểm đặt hàng lại')),
                ('reorder_quantity', models.PositiveIntegerField(default=50, verbose_name='Số lượng đặt lại')),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Nhập hàng cuối')),
                ('last_sold_at', models.DateTimeField(blank=True, null=True, verbose_name='Bán hàng cuối')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá vốn đơn vị')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.product', verbose_name='Sản phẩm')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Tồn kho',
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Sắp hết hàng'), ('out_of_stock', 'Hết hàng'), ('reorder', 'Cần đặt hàng'), ('expiring', 'Sắp hết hạn')], max_length=20, verbose_name='Loại cảnh báo')),
                ('threshold', models.PositiveIntegerField(default=0, verbose_name='Ngưỡng')),
                ('current_quantity', models.IntegerField(verbose_name='SL hiện tại')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Đã xử lý')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Xử lý lúc')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.stockitem', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Cảnh báo tồn kho',
                'verbose_name_plural': 'Cảnh báo tồn kho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('system_quantity', models.IntegerField(verbose_name='SL hệ thống')),
                ('counted_quantity', models.IntegerField(blank=True, null=True, verbose_name='SL thực tế')),
                ('notes', models.TextField(blank=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người kiểm')),
                ('inventory_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorycount', verbose_name='Đợt kiểm')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_items', to='inventory.stockitem', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Chi tiết kiểm kho',
                'verbose_name_plural': 'Chi tiết kiểm kho',
                'unique_together': {('inventory_count', 'stock')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('movement_type', models.CharField(choices=[('in', 'Nhập'), ('out', 'Xuất'), ('reserve', 'Đặt trước'), ('release', 'Giải phóng'), ('adjustment', 'Điều chỉnh'), ('transfer', 'Chuyển kho')], default='adjustment', max_length=20, verbose_name='Loại')),
                ('quantity_change', models.IntegerField(help_text='Dương = nhập, Âm = xuất', verbose_name='Thay đổi số lượng')),
                ('quantity_before', models.IntegerField(blank=True, null=True, verbose_name='SL trước')),
                ('quantity_after', models.IntegerField(blank=True, null=True, verbose_name='SL sau')),
                ('reason', models.CharField(choices=[('purchase', 'Nhập hàng'), ('sale', 'Bán hàng'), ('return', 'Trả hàng'), ('adjustment', 'Điều chỉnh'), ('reservation', 'Đặt trước'), ('release', 'Giải phóng'), ('damage', 'Hư hỏng/Mất'), ('transfer_in', 'Nhận chuyển kho'), ('transfer_out', 'Chuyển kho đi'), ('initial', 'Tồn kho đầu'), ('expired', 'Hết hạn')], max_length=20, verbose_name='Lý do')),
                ('reference', models.CharField(blank=True, db_index=True, help_text='Mã đơn hàng, mã nhập hàng, v.v.', max_length=100, verbose_name='Tham chiếu')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá vốn đơn vị')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockitem', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Lịch sử kho',
                'verbose_name_plural': 'Lịch sử kho',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock', '-created_at'], name='inventory_s_stock_i_cee363_idx'), models.Index(fields=['reason', '-created_at'], name='inventory_s_reason_748aca_idx'), models.Index(fields=['reference'], name='inventory_s_referen_16defd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['product'], name='inventory_s_product_6430b7_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['warehouse', 'quantity'], name='inventory_s_warehou_f597d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('product', 'warehouse')},
        ),
    ]
