# Generated by Django 5.2.9 on 2026-01-03 17:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(error_messages={'unique': 'Email này đã được sử dụng'}, max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(blank=True, max_length=150, unique=True, verbose_name='Username')),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu bằng +84 hoặc 0, theo sau bởi 9 chữ số.', regex='^(\\+84|0)[3-9]\\d{8}$')], verbose_name='Số điện thoại')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Phường/Xã')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Quận/Huyện')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('province_id', models.IntegerField(blank=True, help_text='GHN Province ID', null=True)),
                ('district_id', models.IntegerField(blank=True, help_text='GHN District ID', null=True)),
                ('ward_code', models.CharField(blank=True, help_text='GHN Ward Code', max_length=20)),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email đã xác thực')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xác thực email')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email thông báo')),
                ('order_updates', models.BooleanField(default=True, verbose_name='Cập nhật đơn hàng')),
                ('promotional_emails', models.BooleanField(default=False, verbose_name='Email khuyến mãi')),
                ('newsletter', models.BooleanField(default=False, verbose_name='Bản tin')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push')),
                ('push_order_updates', models.BooleanField(default=True)),
                ('push_promotions', models.BooleanField(default=False)),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='SMS')),
                ('sms_order_updates', models.BooleanField(default=True)),
                ('language', models.CharField(default='vi', max_length=10, verbose_name='Ngôn ngữ')),
                ('currency', models.CharField(default='VND', max_length=3, verbose_name='Tiền tệ')),
                ('timezone_name', models.CharField(default='Asia/Ho_Chi_Minh', max_length=50)),
                ('profile_visibility', models.CharField(choices=[('public', 'Công khai'), ('private', 'Riêng tư')], default='private', max_length=20)),
                ('show_order_history', models.BooleanField(default=False)),
                ('allow_review_public', models.BooleanField(default=True)),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA')),
                ('login_notification', models.BooleanField(default=True, verbose_name='Thông báo đăng nhập')),
            ],
            options={
                'verbose_name': 'Cài đặt người dùng',
                'verbose_name_plural': 'Cài đặt người dùng',
            },
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('reason', models.TextField(blank=True, verbose_name='Lý do')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('approved', 'Đã duyệt'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Lên lịch xóa')),
                ('grace_period_days', models.PositiveIntegerField(default=30, verbose_name='Ngày ân hạn')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('data_exported', models.BooleanField(default=False)),
                ('export_url', models.URLField(blank=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Yêu cầu xóa tài khoản',
                'verbose_name_plural': 'Yêu cầu xóa tài khoản',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('email', models.EmailField(max_length=254, verbose_name='Email đăng nhập')),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('failed', 'Thất bại'), ('blocked', 'Bị chặn')], max_length=20, verbose_name='Trạng thái')),
                ('fail_reason', models.CharField(blank=True, choices=[('invalid_password', 'Sai mật khẩu'), ('account_locked', 'Tài khoản bị khóa'), ('account_inactive', 'Tài khoản không hoạt động'), ('email_not_verified', 'Email chưa xác thực'), ('captcha_failed', 'CAPTCHA không hợp lệ'), ('rate_limited', 'Quá nhiều lần thử')], max_length=30, verbose_name='Lý do thất bại')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lịch sử đăng nhập',
                'verbose_name_plural': 'Lịch sử đăng nhập',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('google', 'Google')], max_length=20, verbose_name='Nhà cung cấp')),
                ('uid', models.CharField(max_length=255, verbose_name='Provider User ID')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu bổ sung')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Tài khoản liên kết',
                'verbose_name_plural': 'Tài khoản liên kết',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('label', models.CharField(default='Home', help_text='Ví dụ: Nhà, Công ty', max_length=50, verbose_name='Nhãn')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Tên người nhận')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu bằng +84 hoặc 0, theo sau bởi 9 chữ số.', regex='^(\\+84|0)[3-9]\\d{8}$')], verbose_name='Số điện thoại')),
                ('street', models.CharField(max_length=255, verbose_name='Địa chỉ chi tiết')),
                ('ward', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('city', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('province_id', models.IntegerField(verbose_name='Mã tỉnh GHN')),
                ('district_id', models.IntegerField(verbose_name='Mã quận GHN')),
                ('ward_code', models.CharField(max_length=20, verbose_name='Mã phường GHN')),
                ('is_default', models.BooleanField(default=False, verbose_name='Địa chỉ mặc định')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Địa chỉ giao hàng',
                'verbose_name_plural': 'Địa chỉ giao hàng',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('refresh_token_hash', models.CharField(blank=True, max_length=64)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Phiên đăng nhập',
                'verbose_name_plural': 'Phiên đăng nhập',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='identity_us_email_bcdd3b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='identity_us_phone_24ee25_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted'], name='identity_us_is_dele_feffbc_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', '-created_at'], name='identity_lo_user_id_5211a9_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['email', '-created_at'], name='identity_lo_email_e8bf2a_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['ip_address', '-created_at'], name='identity_lo_ip_addr_2652e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('provider', 'uid')},
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='identity_us_user_id_cb56d2_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='identity_us_session_75c6eb_idx'),
        ),
    ]
