# Generated by Django 5.2.9 on 2026-01-03 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('vnpay', 'VNPay'), ('momo', 'Ví MoMo')], db_index=True, max_length=20, verbose_name='Phương thức')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền')),
                ('currency', models.CharField(default='VND', max_length=3, verbose_name='Đơn vị tiền')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('processing', 'Đang xử lý'), ('awaiting_capture', 'Chờ capture'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy'), ('expired', 'Hết hạn'), ('partial_refund', 'Hoàn một phần'), ('refunded', 'Đã hoàn tiền')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Mã giao dịch gateway')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255, verbose_name='Mã giao dịch provider')),
                ('payment_url', models.TextField(blank=True, verbose_name='URL thanh toán')),
                ('qr_code_url', models.TextField(blank=True, verbose_name='QR Code URL')),
                ('provider_data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu provider')),
                ('webhook_data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu webhook')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Lý do thất bại')),
                ('failure_code', models.CharField(blank=True, max_length=50, verbose_name='Mã lỗi')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='Số lần thử lại')),
                ('max_retries', models.PositiveSmallIntegerField(default=3, verbose_name='Số lần thử tối đa')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Hết hạn lúc')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Thanh toán lúc')),
                ('captured_at', models.DateTimeField(blank=True, null=True, verbose_name='Capture lúc')),
                ('refunded_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền đã hoàn')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_info', models.JSONField(blank=True, default=dict, verbose_name='Device info')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('event', models.CharField(max_length=50, verbose_name='Sự kiện')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Log thanh toán',
                'verbose_name_plural': 'Log thanh toán',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('card', 'Thẻ tín dụng/ghi nợ'), ('bank', 'Tài khoản ngân hàng'), ('wallet', 'Ví điện tử')], max_length=20, verbose_name='Loại')),
                ('provider', models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('vnpay', 'VNPay'), ('momo', 'Ví MoMo')], max_length=20, verbose_name='Provider')),
                ('display_name', models.CharField(max_length=100, verbose_name='Tên hiển thị')),
                ('last_four', models.CharField(blank=True, max_length=4, verbose_name='4 số cuối')),
                ('brand', models.CharField(blank=True, max_length=30, verbose_name='Thương hiệu')),
                ('token', models.CharField(max_length=255, verbose_name='Token')),
                ('is_default', models.BooleanField(default=False, verbose_name='Mặc định')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Hết hạn')),
                ('billing_name', models.CharField(blank=True, max_length=100)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Phương thức thanh toán',
                'verbose_name_plural': 'Phương thức thanh toán',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_type', models.CharField(choices=[('full', 'Hoàn toàn bộ'), ('partial', 'Hoàn một phần')], default='full', max_length=20, verbose_name='Loại hoàn')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền hoàn')),
                ('reason', models.CharField(choices=[('customer_request', 'Khách yêu cầu'), ('duplicate', 'Thanh toán trùng'), ('fraudulent', 'Gian lận'), ('order_cancelled', 'Đơn hàng bị hủy'), ('return', 'Hoàn trả hàng'), ('other', 'Khác')], default='other', max_length=30, verbose_name='Lý do')),
                ('reason_detail', models.TextField(blank=True, verbose_name='Chi tiết lý do')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], db_index=True, default='pending', max_length=20)),
                ('refund_id', models.CharField(blank=True, max_length=255, verbose_name='Mã hoàn tiền gateway')),
                ('provider_refund_id', models.CharField(blank=True, max_length=255, verbose_name='Mã hoàn tiền provider')),
                ('provider_data', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hoàn tiền',
                'verbose_name_plural': 'Hoàn tiền',
                'ordering': ['-created_at'],
            },
        ),
    ]
