# Generated by Django 5.2.9 on 2026-01-09 02:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Refund ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('reason', models.CharField(choices=[('customer_request', 'Customer Request'), ('duplicate', 'Duplicate Payment'), ('fraudulent', 'Fraudulent'), ('order_cancelled', 'Order Cancelled'), ('product_issue', 'Product Issue'), ('other', 'Other')], default='customer_request', max_length=30, verbose_name='Reason')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Refund Amount')),
                ('is_partial', models.BooleanField(default=False, verbose_name='Partial Refund')),
                ('gateway_refund_id', models.CharField(blank=True, max_length=200, verbose_name='Gateway Refund ID')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='Gateway Response')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
            ],
            options={
                'verbose_name': 'Payment Refund',
                'verbose_name_plural': 'Payment Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Transaction ID')),
                ('gateway', models.CharField(choices=[('cod', 'Cash on Delivery'), ('vnpay', 'VNPay'), ('momo', 'MoMo'), ('stripe', 'Stripe')], db_index=True, max_length=20, verbose_name='Payment Gateway')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Amount')),
                ('currency', models.CharField(default='VND', max_length=3, verbose_name='Currency')),
                ('fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Transaction Fee')),
                ('gateway_transaction_id', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Gateway Txn ID')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='Gateway Response')),
                ('payment_url', models.URLField(blank=True, max_length=2000, verbose_name='Payment URL')),
                ('return_url', models.URLField(blank=True, max_length=500, verbose_name='Return URL')),
                ('initiated_at', models.DateTimeField(auto_now_add=True, verbose_name='Initiated At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('error_code', models.CharField(blank=True, max_length=50, verbose_name='Error Code')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
