# Generated by Django 5.2.9 on 2026-01-03 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('reason', models.CharField(choices=[('failed_logins', 'Đăng nhập sai nhiều lần'), ('suspicious', 'Hoạt động đáng ngờ'), ('admin', 'Khóa bởi admin'), ('brute_force', 'Tấn công brute force'), ('compromised', 'Tài khoản bị xâm phạm')], max_length=20, verbose_name='Lý do')),
                ('locked_until', models.DateTimeField(verbose_name='Khóa đến')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_accounts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lockouts', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Khóa tài khoản',
                'verbose_name_plural': 'Khóa tài khoản',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('key_prefix', models.CharField(db_index=True, max_length=8)),
                ('key_hash', models.CharField(max_length=64)),
                ('permission', models.CharField(choices=[('read', 'Read Only'), ('write', 'Read/Write'), ('admin', 'Admin')], default='read', max_length=10, verbose_name='Quyền')),
                ('allowed_ips', models.JSONField(blank=True, default=list)),
                ('rate_limit', models.PositiveIntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('reason', models.CharField(choices=[('brute_force', 'Tấn công brute force'), ('spam', 'Spam'), ('abuse', 'Lạm dụng'), ('fraud', 'Gian lận'), ('manual', 'Thêm thủ công')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('block_count', models.PositiveIntegerField(default=0)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP Blacklist',
                'verbose_name_plural': 'IP Blacklist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('device_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=64)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('trusted_at', models.DateTimeField(auto_now_add=True)),
                ('trusted_until', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Thiết bị tin cậy',
                'verbose_name_plural': 'Thiết bị tin cậy',
                'ordering': ['-last_used'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Đã kích hoạt')),
                ('method', models.CharField(choices=[('totp', 'Authenticator App'), ('email', 'Email OTP'), ('sms', 'SMS OTP')], default='totp', max_length=10, verbose_name='Phương thức')),
                ('secret', models.CharField(blank=True, max_length=64, verbose_name='Secret Key')),
                ('backup_codes', models.JSONField(blank=True, default=list, verbose_name='Mã dự phòng')),
                ('backup_codes_count', models.PositiveSmallIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Sử dụng lần cuối')),
                ('setup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_email', models.EmailField(blank=True, max_length=254, verbose_name='Email khôi phục')),
                ('recovery_phone', models.CharField(blank=True, max_length=15, verbose_name='SĐT khôi phục')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Cấu hình 2FA',
                'verbose_name_plural': 'Cấu hình 2FA',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Địa chỉ IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('success', models.BooleanField(verbose_name='Thành công')),
                ('failure_reason', models.CharField(blank=True, max_length=50, verbose_name='Lý do thất bại')),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('required_2fa', models.BooleanField(default=False)),
                ('passed_2fa', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lịch sử đăng nhập',
                'verbose_name_plural': 'Lịch sử đăng nhập',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', '-created_at'], name='security_lo_email_a5a7f3_idx'), models.Index(fields=['ip_address', '-created_at'], name='security_lo_ip_addr_072023_idx'), models.Index(fields=['user', '-created_at'], name='security_lo_user_id_bdf3d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('event_type', models.CharField(choices=[('login_success', 'Đăng nhập thành công'), ('login_failed', 'Đăng nhập thất bại'), ('logout', 'Đăng xuất'), ('2fa_enabled', 'Bật 2FA'), ('2fa_disabled', 'Tắt 2FA'), ('2fa_verified', 'Xác thực 2FA'), ('2fa_failed', '2FA thất bại'), ('backup_used', 'Dùng mã dự phòng'), ('password_changed', 'Đổi mật khẩu'), ('password_reset', 'Reset mật khẩu'), ('email_changed', 'Đổi email'), ('account_locked', 'Khóa tài khoản'), ('account_unlocked', 'Mở khóa tài khoản'), ('api_key_created', 'Tạo API key'), ('api_key_revoked', 'Thu hồi API key'), ('device_trusted', 'Trust thiết bị'), ('device_revoked', 'Thu hồi trust'), ('new_device', 'Login thiết bị mới'), ('suspicious', 'Hoạt động đáng ngờ'), ('ip_blocked', 'Block IP'), ('brute_force', 'Phát hiện brute force')], db_index=True, max_length=30, verbose_name='Loại sự kiện')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audits', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Security Audit Log',
                'verbose_name_plural': 'Security Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='security_se_user_id_a067e5_idx'), models.Index(fields=['event_type', '-created_at'], name='security_se_event_t_6201c2_idx'), models.Index(fields=['ip_address', '-created_at'], name='security_se_ip_addr_5b161e_idx'), models.Index(fields=['severity', '-created_at'], name='security_se_severit_1bd6ee_idx')],
            },
        ),
    ]
