# Generated by Django 5.2.9 on 2026-01-09 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghn_id', models.IntegerField(db_index=True, unique=True, verbose_name='GHN Province ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_extension', models.JSONField(blank=True, default=list, verbose_name='Name Extensions')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghn_id', models.IntegerField(db_index=True, unique=True, verbose_name='GHN District ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_extension', models.JSONField(blank=True, default=list, verbose_name='Name Extensions')),
                ('support_type', models.IntegerField(default=0)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghn_code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='GHN Ward Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_extension', models.JSONField(blank=True, default=list, verbose_name='Name Extensions')),
                ('support_type', models.IntegerField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='core.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
                'ordering': ['name'],
            },
        ),
    ]
