# Generated by Django 5.2.9 on 2026-01-03 17:06

import apps.common.core.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên Flash Sale')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='flash_sales/', verbose_name='Banner')),
                ('start_time', models.DateTimeField(verbose_name='Bắt đầu')),
                ('end_time', models.DateTimeField(verbose_name='Kết thúc')),
                ('status', models.CharField(choices=[('scheduled', 'Đã lên lịch'), ('active', 'Đang diễn ra'), ('ended', 'Đã kết thúc'), ('cancelled', 'Đã hủy')], default='scheduled', max_length=20, verbose_name='Trạng thái')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
            ],
            options={
                'verbose_name': 'Flash Sale',
                'verbose_name_plural': 'Flash Sale',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Phụ đề')),
                ('image', models.ImageField(upload_to=apps.common.core.storage.banner_image_path, verbose_name='Hình ảnh')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to=apps.common.core.storage.banner_image_path, verbose_name='Hình mobile')),
                ('link_url', models.URLField(blank=True, verbose_name='Link URL')),
                ('link_text', models.CharField(blank=True, max_length=50, verbose_name='Text nút')),
                ('position', models.CharField(choices=[('hero', 'Hero (chính)'), ('sidebar', 'Sidebar'), ('category', 'Danh mục'), ('popup', 'Popup'), ('footer', 'Footer')], default='hero', max_length=20, verbose_name='Vị trí')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Hoạt động')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Lượt click')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Tên coupon')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('discount_type', models.CharField(choices=[('percentage', 'Phần trăm'), ('fixed', 'Số tiền cố định'), ('free_shipping', 'Miễn phí vận chuyển')], default='percentage', max_length=20, verbose_name='Loại giảm giá')),
                ('discount_value', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá trị giảm')),
                ('min_order_value', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá trị đơn tối thiểu')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giảm tối đa')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Giới hạn tổng')),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, verbose_name='Giới hạn/người')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Đã sử dụng')),
                ('valid_from', models.DateTimeField(verbose_name='Hiệu lực từ')),
                ('valid_until', models.DateTimeField(verbose_name='Hiệu lực đến')),
                ('apply_to', models.CharField(choices=[('all', 'Tất cả sản phẩm'), ('category', 'Theo danh mục'), ('product', 'Sản phẩm cụ thể'), ('brand', 'Theo thương hiệu')], default='all', max_length=20, verbose_name='Áp dụng cho')),
                ('first_order_only', models.BooleanField(default=False, verbose_name='Chỉ đơn đầu tiên')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Hoạt động')),
                ('is_public', models.BooleanField(default=True, verbose_name='Hiển thị công khai')),
                ('applicable_brands', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.brand', verbose_name='Thương hiệu áp dụng')),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.category', verbose_name='Danh mục áp dụng')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.product', verbose_name='Sản phẩm áp dụng')),
                ('specific_users', models.ManyToManyField(blank=True, related_name='exclusive_coupons', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng cụ thể')),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Mã giảm giá',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên campaign')),
                ('description', models.TextField(blank=True)),
                ('campaign_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('social', 'Social Media'), ('ads', 'Quảng cáo')], default='email', max_length=20, verbose_name='Loại')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('scheduled', 'Đã lên lịch'), ('active', 'Đang chạy'), ('paused', 'Tạm dừng'), ('completed', 'Hoàn thành')], default='draft', max_length=20)),
                ('target_audience', models.JSONField(blank=True, default=dict, verbose_name='Đối tượng')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Đã gửi')),
                ('open_count', models.PositiveIntegerField(default=0, verbose_name='Đã mở')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Đã click')),
                ('conversion_count', models.PositiveIntegerField(default=0, verbose_name='Chuyển đổi')),
                ('revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Doanh thu')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='marketing.coupon')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('order_id', models.UUIDField(blank=True, null=True, verbose_name='Đơn hàng')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền giảm')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='marketing.coupon', verbose_name='Coupon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lịch sử sử dụng coupon',
                'verbose_name_plural': 'Lịch sử sử dụng coupon',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('flash_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá Flash Sale')),
                ('original_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá gốc')),
                ('quantity_limit', models.PositiveIntegerField(default=0, help_text='0 = không giới hạn', verbose_name='Số lượng giới hạn')),
                ('quantity_sold', models.PositiveIntegerField(default=0, verbose_name='Đã bán')),
                ('per_user_limit', models.PositiveIntegerField(default=1, verbose_name='Giới hạn/người')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketing.flashsale', verbose_name='Flash Sale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sale_items', to='catalog.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm Flash Sale',
                'verbose_name_plural': 'Sản phẩm Flash Sale',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='marketing_c_code_dee8bf_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='marketing_c_is_acti_6c60cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flashsaleitem',
            unique_together={('flash_sale', 'product')},
        ),
    ]
