# Generated by Django 5.2.9 on 2026-01-09 04:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='flash_sales/', verbose_name='Banner')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Flash Sale',
                'verbose_name_plural': 'Flash Sales',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Image')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Mobile Image')),
                ('link_url', models.URLField(blank=True, verbose_name='Link URL')),
                ('link_text', models.CharField(blank=True, max_length=50, verbose_name='Button Text')),
                ('position', models.CharField(choices=[('hero', 'Hero'), ('sidebar', 'Sidebar'), ('category', 'Category'), ('popup', 'Popup'), ('footer', 'Footer')], default='hero', max_length=20, verbose_name='Position')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('free_shipping', 'Free Shipping')], default='percentage', max_length=20, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Discount Value')),
                ('min_order_value', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Min Order Value')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Max Discount')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Usage Limit')),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, verbose_name='Limit per User')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Used Count')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(verbose_name='Valid Until')),
                ('apply_to', models.CharField(choices=[('all', 'All Products'), ('category', 'By Category'), ('product', 'Specific Products'), ('brand', 'By Brand')], default='all', max_length=20, verbose_name='Apply To')),
                ('first_order_only', models.BooleanField(default=False, verbose_name='First Order Only')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('applicable_brands', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.brand', verbose_name='Brands')),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.category', verbose_name='Categories')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.product', verbose_name='Products')),
                ('specific_users', models.ManyToManyField(blank=True, related_name='exclusive_coupons', to=settings.AUTH_USER_MODEL, verbose_name='Specific Users')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True)),
                ('campaign_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('social', 'Social Media'), ('ads', 'Ads')], default='email', max_length=20, verbose_name='Type')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('target_audience', models.JSONField(blank=True, default=dict, verbose_name='Target Audience')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Sent')),
                ('open_count', models.PositiveIntegerField(default=0, verbose_name='Opened')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Clicked')),
                ('conversion_count', models.PositiveIntegerField(default=0, verbose_name='Conversions')),
                ('revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Revenue')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='marketing.coupon')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('order_id', models.UUIDField(blank=True, null=True, verbose_name='Order')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Discount Amount')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='marketing.coupon', verbose_name='Coupon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('flash_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Flash Price')),
                ('original_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Original Price')),
                ('quantity_limit', models.PositiveIntegerField(default=0, help_text='0 = unlimited', verbose_name='Quantity Limit')),
                ('quantity_sold', models.PositiveIntegerField(default=0, verbose_name='Sold')),
                ('per_user_limit', models.PositiveIntegerField(default=1, verbose_name='Limit per User')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketing.flashsale', verbose_name='Flash Sale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sale_items', to='catalog.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Flash Sale Item',
                'verbose_name_plural': 'Flash Sale Items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='marketing_c_code_dee8bf_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='marketing_c_is_acti_6c60cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flashsaleitem',
            unique_together={('flash_sale', 'product')},
        ),
    ]
