# Generated by Django 5.2.9 on 2026-01-09 02:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('notification_type', models.CharField(choices=[('order_placed', 'New Order'), ('order_confirmed', 'Order Confirmed'), ('order_shipped', 'Shipping'), ('order_delivered', 'Delivered'), ('order_cancelled', 'Order Cancelled'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('refund_processed', 'Refund Processed'), ('welcome', 'Welcome'), ('email_verified', 'Email Verified'), ('password_changed', 'Password Changed'), ('new_login', 'New Login'), ('security_alert', 'Security Alert'), ('promotion', 'Promotion'), ('flash_sale', 'Flash Sale'), ('price_drop', 'Price Drop'), ('back_in_stock', 'Back In Stock'), ('review_reply', 'Review Reply'), ('review_helpful', 'Helpful Review'), ('system', 'System Notification'), ('announcement', 'Announcement')], max_length=30, unique=True, verbose_name='Type')),
                ('title_template', models.CharField(max_length=200, verbose_name='Title Template')),
                ('message_template', models.TextField(verbose_name='Message Template')),
                ('action_url_template', models.CharField(blank=True, max_length=500)),
                ('action_text', models.CharField(blank=True, max_length=50)),
                ('email_subject_template', models.CharField(blank=True, max_length=200)),
                ('email_template_name', models.CharField(blank=True, max_length=100)),
                ('push_title_template', models.CharField(blank=True, max_length=100)),
                ('push_body_template', models.CharField(blank=True, max_length=200)),
                ('sms_template', models.CharField(blank=True, max_length=160)),
                ('default_channels', models.JSONField(default=list)),
                ('default_priority', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('order_placed', 'New Order'), ('order_confirmed', 'Order Confirmed'), ('order_shipped', 'Shipping'), ('order_delivered', 'Delivered'), ('order_cancelled', 'Order Cancelled'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('refund_processed', 'Refund Processed'), ('welcome', 'Welcome'), ('email_verified', 'Email Verified'), ('password_changed', 'Password Changed'), ('new_login', 'New Login'), ('security_alert', 'Security Alert'), ('promotion', 'Promotion'), ('flash_sale', 'Flash Sale'), ('price_drop', 'Price Drop'), ('back_in_stock', 'Back In Stock'), ('review_reply', 'Review Reply'), ('review_helpful', 'Helpful Review'), ('system', 'System Notification'), ('announcement', 'Announcement')], db_index=True, max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('image_url', models.URLField(blank=True, verbose_name='Image')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='Action URL')),
                ('action_text', models.CharField(blank=True, max_length=50, verbose_name='Button Text')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Extra Data')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('channels_sent', models.JSONField(blank=True, default=list)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('push', 'Push Notification'), ('sms', 'SMS')], max_length=10, verbose_name='Channel')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=20, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notification', verbose_name='Notification')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('notification_type', models.CharField(choices=[('order_placed', 'New Order'), ('order_confirmed', 'Order Confirmed'), ('order_shipped', 'Shipping'), ('order_delivered', 'Delivered'), ('order_cancelled', 'Order Cancelled'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('refund_processed', 'Refund Processed'), ('welcome', 'Welcome'), ('email_verified', 'Email Verified'), ('password_changed', 'Password Changed'), ('new_login', 'New Login'), ('security_alert', 'Security Alert'), ('promotion', 'Promotion'), ('flash_sale', 'Flash Sale'), ('price_drop', 'Price Drop'), ('back_in_stock', 'Back In Stock'), ('review_reply', 'Review Reply'), ('review_helpful', 'Helpful Review'), ('system', 'System Notification'), ('announcement', 'Announcement')], max_length=30, verbose_name='Type')),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_f0e72c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_f77590_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'notification_type')},
        ),
    ]
