# Generated by Django 5.2.9 on 2026-01-03 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('notification_type', models.CharField(choices=[('order_placed', 'Đơn hàng mới'), ('order_confirmed', 'Đơn hàng đã xác nhận'), ('order_shipped', 'Đang giao hàng'), ('order_delivered', 'Đã giao hàng'), ('order_cancelled', 'Đơn hàng đã hủy'), ('payment_success', 'Thanh toán thành công'), ('payment_failed', 'Thanh toán thất bại'), ('refund_processed', 'Hoàn tiền thành công'), ('welcome', 'Chào mừng'), ('email_verified', 'Email đã xác thực'), ('password_changed', 'Đổi mật khẩu'), ('new_login', 'Đăng nhập mới'), ('security_alert', 'Cảnh báo bảo mật'), ('promotion', 'Khuyến mãi'), ('flash_sale', 'Flash Sale'), ('price_drop', 'Giảm giá sản phẩm'), ('back_in_stock', 'Có hàng trở lại'), ('review_reply', 'Trả lời đánh giá'), ('review_helpful', 'Đánh giá hữu ích'), ('system', 'Thông báo hệ thống'), ('announcement', 'Thông báo chung')], max_length=30, unique=True, verbose_name='Loại')),
                ('title_template', models.CharField(max_length=200, verbose_name='Template tiêu đề')),
                ('message_template', models.TextField(verbose_name='Template nội dung')),
                ('action_url_template', models.CharField(blank=True, max_length=500)),
                ('action_text', models.CharField(blank=True, max_length=50)),
                ('email_subject_template', models.CharField(blank=True, max_length=200)),
                ('email_template_name', models.CharField(blank=True, max_length=100)),
                ('push_title_template', models.CharField(blank=True, max_length=100)),
                ('push_body_template', models.CharField(blank=True, max_length=200)),
                ('sms_template', models.CharField(blank=True, max_length=160)),
                ('default_channels', models.JSONField(default=list)),
                ('default_priority', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Template thông báo',
                'verbose_name_plural': 'Template thông báo',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_placed', 'Đơn hàng mới'), ('order_confirmed', 'Đơn hàng đã xác nhận'), ('order_shipped', 'Đang giao hàng'), ('order_delivered', 'Đã giao hàng'), ('order_cancelled', 'Đơn hàng đã hủy'), ('payment_success', 'Thanh toán thành công'), ('payment_failed', 'Thanh toán thất bại'), ('refund_processed', 'Hoàn tiền thành công'), ('welcome', 'Chào mừng'), ('email_verified', 'Email đã xác thực'), ('password_changed', 'Đổi mật khẩu'), ('new_login', 'Đăng nhập mới'), ('security_alert', 'Cảnh báo bảo mật'), ('promotion', 'Khuyến mãi'), ('flash_sale', 'Flash Sale'), ('price_drop', 'Giảm giá sản phẩm'), ('back_in_stock', 'Có hàng trở lại'), ('review_reply', 'Trả lời đánh giá'), ('review_helpful', 'Đánh giá hữu ích'), ('system', 'Thông báo hệ thống'), ('announcement', 'Thông báo chung')], db_index=True, max_length=30, verbose_name='Loại')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('image_url', models.URLField(blank=True, verbose_name='Hình ảnh')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='Link hành động')),
                ('action_text', models.CharField(blank=True, max_length=50, verbose_name='Text nút')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu bổ sung')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Đã đọc')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Đọc lúc')),
                ('channels_sent', models.JSONField(blank=True, default=list)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('channel', models.CharField(choices=[('in_app', 'Trong ứng dụng'), ('email', 'Email'), ('push', 'Push notification'), ('sms', 'SMS')], max_length=10, verbose_name='Kênh')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('sent', 'Đã gửi'), ('failed', 'Thất bại'), ('delivered', 'Đã nhận')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notification', verbose_name='Thông báo')),
            ],
            options={
                'verbose_name': 'Log gửi thông báo',
                'verbose_name_plural': 'Log gửi thông báo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('notification_type', models.CharField(choices=[('order_placed', 'Đơn hàng mới'), ('order_confirmed', 'Đơn hàng đã xác nhận'), ('order_shipped', 'Đang giao hàng'), ('order_delivered', 'Đã giao hàng'), ('order_cancelled', 'Đơn hàng đã hủy'), ('payment_success', 'Thanh toán thành công'), ('payment_failed', 'Thanh toán thất bại'), ('refund_processed', 'Hoàn tiền thành công'), ('welcome', 'Chào mừng'), ('email_verified', 'Email đã xác thực'), ('password_changed', 'Đổi mật khẩu'), ('new_login', 'Đăng nhập mới'), ('security_alert', 'Cảnh báo bảo mật'), ('promotion', 'Khuyến mãi'), ('flash_sale', 'Flash Sale'), ('price_drop', 'Giảm giá sản phẩm'), ('back_in_stock', 'Có hàng trở lại'), ('review_reply', 'Trả lời đánh giá'), ('review_helpful', 'Đánh giá hữu ích'), ('system', 'Thông báo hệ thống'), ('announcement', 'Thông báo chung')], max_length=30, verbose_name='Loại')),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Cài đặt thông báo',
                'verbose_name_plural': 'Cài đặt thông báo',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_f0e72c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_f77590_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'notification_type')},
        ),
    ]
