# Generated by Django 5.2.9 on 2026-01-09 04:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='Request Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('awaiting_return', 'Awaiting Return'), ('received', 'Received'), ('processing_refund', 'Processing Refund'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('reason', models.CharField(choices=[('defective', 'Defective/Damaged'), ('wrong_item', 'Wrong Item'), ('not_as_described', 'Not As Described'), ('missing_parts', 'Missing Parts'), ('size_fit', 'Size/Fit Issue'), ('changed_mind', 'Changed Mind'), ('quality', 'Quality Issue'), ('damaged_shipping', 'Damaged in Shipping'), ('other', 'Other')], max_length=20, verbose_name='Reason')),
                ('description', models.TextField(verbose_name='Description')),
                ('refund_method', models.CharField(choices=[('original', 'Original Payment Method'), ('bank_transfer', 'Bank Transfer'), ('wallet', 'E-Wallet'), ('store_credit', 'Store Credit')], default='original', max_length=20, verbose_name='Refund Method')),
                ('requested_refund', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Requested Refund')),
                ('approved_refund', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Approved Refund')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Bank Name')),
                ('bank_account_number', models.CharField(blank=True, max_length=30, verbose_name='Account Number')),
                ('bank_account_name', models.CharField(blank=True, max_length=100, verbose_name='Account Name')),
                ('return_tracking_code', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Return Tracking')),
                ('return_carrier', models.CharField(blank=True, max_length=50, verbose_name='Return Carrier')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('quality_check_passed', models.BooleanField(null=True, verbose_name='Quality Check')),
                ('quality_check_notes', models.TextField(blank=True, verbose_name='Quality Notes')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Received At')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Refunded At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='orders.order', verbose_name='Order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Return Request',
                'verbose_name_plural': 'Return Requests',
                'ordering': ['-created_at'],
                'permissions': [('can_approve_returns', 'Can approve return requests'), ('can_process_refunds', 'Can process refunds')],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('reason', models.CharField(blank=True, choices=[('defective', 'Defective/Damaged'), ('wrong_item', 'Wrong Item'), ('not_as_described', 'Not As Described'), ('missing_parts', 'Missing Parts'), ('size_fit', 'Size/Fit Issue'), ('changed_mind', 'Changed Mind'), ('quality', 'Quality Issue'), ('damaged_shipping', 'Damaged in Shipping'), ('other', 'Other')], max_length=20, verbose_name='Reason')),
                ('condition', models.CharField(blank=True, max_length=50, verbose_name='Condition')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('accepted_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Accepted Qty')),
                ('refund_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Refund Amount')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.orderitem', verbose_name='Order Item')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnrequest', verbose_name='Return Request')),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
            },
        ),
        migrations.CreateModel(
            name='ReturnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('image', models.ImageField(upload_to='returns/%Y/%m/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='returns.returnrequest', verbose_name='Return Request')),
            ],
            options={
                'verbose_name': 'Return Image',
                'verbose_name_plural': 'Return Images',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('awaiting_return', 'Awaiting Return'), ('received', 'Received'), ('processing_refund', 'Processing Refund'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='returns.returnrequest', verbose_name='Return Request')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['user', '-created_at'], name='returns_ret_user_id_655bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status', '-created_at'], name='returns_ret_status_6a52e1_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order', 'status'], name='returns_ret_order_i_7316d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='returnitem',
            unique_together={('return_request', 'order_item')},
        ),
    ]
