# Generated by Django 5.2.9 on 2026-01-03 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='Mã yêu cầu')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('reviewing', 'Đang xem xét'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('awaiting_return', 'Chờ nhận hàng'), ('received', 'Đã nhận hàng'), ('processing_refund', 'Đang hoàn tiền'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('reason', models.CharField(choices=[('defective', 'Hàng lỗi/hư hỏng'), ('wrong_item', 'Giao sai hàng'), ('not_as_described', 'Không đúng mô tả'), ('missing_parts', 'Thiếu phụ kiện/linh kiện'), ('size_fit', 'Không vừa kích thước'), ('changed_mind', 'Đổi ý'), ('quality', 'Chất lượng không đạt'), ('damaged_shipping', 'Hư hỏng khi vận chuyển'), ('other', 'Lý do khác')], max_length=20, verbose_name='Lý do')),
                ('description', models.TextField(help_text='Mô tả chi tiết về vấn đề với sản phẩm', verbose_name='Mô tả chi tiết')),
                ('refund_method', models.CharField(choices=[('original', 'Hoàn về phương thức gốc'), ('bank_transfer', 'Chuyển khoản ngân hàng'), ('wallet', 'Ví điện tử'), ('store_credit', 'Điểm thưởng/Credit')], default='original', max_length=20, verbose_name='Phương thức hoàn tiền')),
                ('requested_refund', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền yêu cầu hoàn')),
                ('approved_refund', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền được duyệt')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Ngân hàng')),
                ('bank_account_number', models.CharField(blank=True, max_length=30, verbose_name='Số tài khoản')),
                ('bank_account_name', models.CharField(blank=True, max_length=100, verbose_name='Tên chủ tài khoản')),
                ('return_tracking_code', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Mã vận đơn trả hàng')),
                ('return_carrier', models.CharField(blank=True, max_length=50, verbose_name='Đơn vị vận chuyển')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Ghi chú admin')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Lý do từ chối')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xử lý')),
                ('quality_check_passed', models.BooleanField(null=True, verbose_name='Kiểm tra chất lượng')),
                ('quality_check_notes', models.TextField(blank=True, verbose_name='Ghi chú kiểm tra')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian nhận hàng')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn tiền')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn tất')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='orders.order', verbose_name='Đơn hàng')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to='billing.refund', verbose_name='Hoàn tiền')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Yêu cầu hoàn trả',
                'verbose_name_plural': 'Yêu cầu hoàn trả',
                'ordering': ['-created_at'],
                'permissions': [('can_approve_returns', 'Can approve return requests'), ('can_process_refunds', 'Can process refunds for returns')],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng trả')),
                ('reason', models.CharField(blank=True, choices=[('defective', 'Hàng lỗi/hư hỏng'), ('wrong_item', 'Giao sai hàng'), ('not_as_described', 'Không đúng mô tả'), ('missing_parts', 'Thiếu phụ kiện/linh kiện'), ('size_fit', 'Không vừa kích thước'), ('changed_mind', 'Đổi ý'), ('quality', 'Chất lượng không đạt'), ('damaged_shipping', 'Hư hỏng khi vận chuyển'), ('other', 'Lý do khác')], max_length=20, verbose_name='Lý do cụ thể')),
                ('condition', models.CharField(blank=True, max_length=50, verbose_name='Tình trạng sản phẩm')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('accepted_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số lượng chấp nhận')),
                ('refund_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền hoàn cho item')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.orderitem', verbose_name='Sản phẩm đơn hàng')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnrequest', verbose_name='Yêu cầu hoàn trả')),
            ],
            options={
                'verbose_name': 'Sản phẩm hoàn trả',
                'verbose_name_plural': 'Sản phẩm hoàn trả',
            },
        ),
        migrations.CreateModel(
            name='ReturnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('image', models.ImageField(upload_to='returns/%Y/%m/', verbose_name='Hình ảnh')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Chú thích')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='returns.returnrequest', verbose_name='Yêu cầu hoàn trả')),
            ],
            options={
                'verbose_name': 'Hình ảnh hoàn trả',
                'verbose_name_plural': 'Hình ảnh hoàn trả',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('reviewing', 'Đang xem xét'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('awaiting_return', 'Chờ nhận hàng'), ('received', 'Đã nhận hàng'), ('processing_refund', 'Đang hoàn tiền'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy')], max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thay đổi')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='returns.returnrequest', verbose_name='Yêu cầu hoàn trả')),
            ],
            options={
                'verbose_name': 'Lịch sử trạng thái',
                'verbose_name_plural': 'Lịch sử trạng thái',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['user', '-created_at'], name='returns_ret_user_id_655bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status', '-created_at'], name='returns_ret_status_6a52e1_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order', 'status'], name='returns_ret_order_i_7316d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='returnitem',
            unique_together={('return_request', 'order_item')},
        ),
    ]
