# Generated by Django 5.2.9 on 2026-01-09 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_with_type', models.CharField(max_length=150, verbose_name='Full Name')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=30, verbose_name='Type')),
                ('search_slug', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Search Slug')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='Path')),
                ('path_with_type', models.CharField(blank=True, max_length=300, verbose_name='Full Path')),
                ('ghn_id', models.IntegerField(blank=True, null=True, verbose_name='GHN Province ID')),
                ('ghtk_id', models.CharField(blank=True, max_length=20, verbose_name='GHTK Province ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['search_slug'], name='locations_p_search__476f11_idx')],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_with_type', models.CharField(max_length=150, verbose_name='Full Name')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=30, verbose_name='Type')),
                ('search_slug', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Search Slug')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='Path')),
                ('path_with_type', models.CharField(blank=True, max_length=300, verbose_name='Full Path')),
                ('ghn_id', models.IntegerField(blank=True, null=True, verbose_name='GHN District ID')),
                ('ghtk_id', models.CharField(blank=True, max_length=20, verbose_name='GHTK District ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='locations.province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['province', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_with_type', models.CharField(max_length=150, verbose_name='Full Name')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=30, verbose_name='Type')),
                ('search_slug', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Search Slug')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='Path')),
                ('path_with_type', models.CharField(blank=True, max_length=500, verbose_name='Full Path')),
                ('ghn_code', models.CharField(blank=True, max_length=20, verbose_name='GHN Ward Code')),
                ('ghtk_id', models.CharField(blank=True, max_length=20, verbose_name='GHTK Ward ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='locations.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
                'ordering': ['district', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['province', 'name'], name='locations_d_provinc_59a186_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['search_slug'], name='locations_d_search__f5ea43_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['district', 'name'], name='locations_w_distric_90b274_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['search_slug'], name='locations_w_search__761f4b_idx'),
        ),
    ]
