# Generated by Django 5.2.9 on 2026-01-03 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('facebook', 'Facebook'), ('apple', 'Apple'), ('discord', 'Discord')], max_length=20, unique=True, verbose_name='Provider')),
                ('client_id', models.CharField(max_length=200, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=200, verbose_name='Client Secret')),
                ('authorize_url', models.URLField(verbose_name='Authorize URL')),
                ('token_url', models.URLField(verbose_name='Token URL')),
                ('userinfo_url', models.URLField(verbose_name='User Info URL')),
                ('scopes', models.JSONField(default=list, verbose_name='Scopes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_name', models.CharField(blank=True, max_length=50)),
                ('icon_url', models.URLField(blank=True)),
                ('button_color', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'verbose_name': 'OAuth Provider Config',
                'verbose_name_plural': 'OAuth Provider Configs',
            },
        ),
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('state', models.CharField(db_index=True, max_length=64, unique=True)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('facebook', 'Facebook'), ('apple', 'Apple'), ('discord', 'Discord')], max_length=20)),
                ('redirect_uri', models.URLField()),
                ('next_url', models.CharField(blank=True, max_length=500)),
                ('action', models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('link', 'Link Account')], default='login', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth State',
                'verbose_name_plural': 'OAuth States',
            },
        ),
        migrations.CreateModel(
            name='SocialLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('facebook', 'Facebook'), ('apple', 'Apple'), ('discord', 'Discord')], max_length=20)),
                ('provider_user_id', models.CharField(blank=True, max_length=200)),
                ('provider_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('error', 'Error')], max_length=10)),
                ('action', models.CharField(blank=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Login Log',
                'verbose_name_plural': 'Social Login Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('facebook', 'Facebook'), ('apple', 'Apple'), ('discord', 'Discord')], max_length=20, verbose_name='Provider')),
                ('provider_user_id', models.CharField(max_length=200, verbose_name='Provider User ID')),
                ('provider_username', models.CharField(blank=True, max_length=200)),
                ('provider_email', models.EmailField(blank=True, max_length=254)),
                ('provider_name', models.CharField(blank=True, max_length=200)),
                ('provider_avatar', models.URLField(blank=True, max_length=500)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('is_primary', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_connections', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Social Connection',
                'verbose_name_plural': 'Social Connections',
                'indexes': [models.Index(fields=['user', 'provider'], name='social_soci_user_id_2dc07e_idx'), models.Index(fields=['provider', 'provider_user_id'], name='social_soci_provide_21cd51_idx')],
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
