# Generated by Django 5.2.9 on 2026-01-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Session Key')),
                ('expires_at', models.DateTimeField(blank=True, help_text='For guest carts only', null=True, verbose_name='Hết hạn')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='Mã giảm giá')),
                ('coupon_discount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giảm giá từ coupon')),
                ('last_activity_at', models.DateTimeField(auto_now=True, verbose_name='Hoạt động cuối')),
                ('abandonment_email_sent', models.BooleanField(default=False, verbose_name='Đã gửi email nhắc nhở')),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Giỏ hàng',
                'verbose_name_plural': 'Giỏ hàng',
            },
        ),
        migrations.CreateModel(
            name='CartEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('event_type', models.CharField(choices=[('add_item', 'Thêm sản phẩm'), ('update_qty', 'Cập nhật số lượng'), ('remove_item', 'Xóa sản phẩm'), ('apply_coupon', 'Áp dụng mã giảm giá'), ('save_later', 'Lưu để mua sau'), ('checkout_start', 'Bắt đầu thanh toán'), ('checkout_done', 'Hoàn thành thanh toán'), ('abandoned', 'Bỏ giỏ hàng')], max_length=20, verbose_name='Loại sự kiện')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu')),
            ],
            options={
                'verbose_name': 'Sự kiện giỏ hàng',
                'verbose_name_plural': 'Sự kiện giỏ hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Đơn giá')),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá gốc')),
                ('selected_attributes', models.JSONField(blank=True, default=dict, verbose_name='Thuộc tính đã chọn')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong giỏ',
                'verbose_name_plural': 'Sản phẩm trong giỏ',
            },
        ),
        migrations.CreateModel(
            name='SavedForLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm bản ghi được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm bản ghi được cập nhật lần cuối', verbose_name='Ngày cập nhật')),
                ('price_when_saved', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá khi lưu')),
            ],
            options={
                'verbose_name': 'Lưu để mua sau',
                'verbose_name_plural': 'Lưu để mua sau',
            },
        ),
    ]
