# Generated by Django 5.2.9 on 2026-01-09 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Session Key')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='Coupon Code')),
                ('coupon_discount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Coupon Discount')),
                ('last_activity_at', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('abandonment_email_sent', models.BooleanField(default=False, verbose_name='Abandonment Email Sent')),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='CartEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('event_type', models.CharField(choices=[('add_item', 'Add Item'), ('update_qty', 'Update Quantity'), ('remove_item', 'Remove Item'), ('apply_coupon', 'Apply Coupon'), ('save_later', 'Save for Later'), ('checkout_start', 'Checkout Start'), ('checkout_done', 'Checkout Complete'), ('abandoned', 'Abandoned')], max_length=20, verbose_name='Event Type')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Data')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cart.cart', verbose_name='Cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Cart Event',
                'verbose_name_plural': 'Cart Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Unit Price')),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Original Price')),
                ('selected_attributes', models.JSONField(blank=True, default=dict, verbose_name='Attributes')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
        migrations.CreateModel(
            name='SavedForLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('price_when_saved', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Price When Saved')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to='cart.cart', verbose_name='Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_in_carts', to='catalog.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Saved for Later',
                'verbose_name_plural': 'Saved for Later',
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='cart_cart_user_id_b645f9_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key'], name='cart_cart_session_5e1af5_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['last_activity_at'], name='cart_cart_last_ac_39da57_idx'),
        ),
        migrations.AddIndex(
            model_name='cartevent',
            index=models.Index(fields=['cart', '-created_at'], name='cart_cartev_cart_id_008c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='cartevent',
            index=models.Index(fields=['event_type', '-created_at'], name='cart_cartev_event_t_2cf6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='cart_cartit_cart_id_4bd8c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='savedforlater',
            unique_together={('cart', 'product')},
        ),
    ]
